//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial1_PrograIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        public int Id { get; set; }
        public string name { get; set; }
        public decimal costo { get; set; }
        public decimal costo_con_incremento { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int gama_id { get; set; }
        public int fabrica_id { get; set; }
        public int color_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Colore Colore { get; set; }
        public virtual Tipos_gama Tipos_gama { get; set; }
        public virtual Fabrica Fabrica { get; set; }
    }
}
