//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial1_PrograIX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Proga_IX : DbContext
    {
        public DB_Proga_IX()
            : base("name=DB_Proga_IX")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignacion_jugadores> Asignacion_jugadores { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Estadio> Estadios { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Gole> Goles { get; set; }
        public virtual DbSet<Jugadore> Jugadores { get; set; }
        public virtual DbSet<Partido> Partidos { get; set; }
        public virtual DbSet<Registros_empleados> Registros_empleados { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
        public virtual DbSet<Piloto> Pilotos { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Vehiculo> Vehiculos { get; set; }
        public virtual DbSet<Percance> Percances { get; set; }
        public virtual DbSet<Tarifa> Tarifas { get; set; }
    }
}
