//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial1_PrograIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partido()
        {
            this.Goles = new HashSet<Gole>();
            this.Tarjetas = new HashSet<Tarjeta>();
        }
    
        public int Id { get; set; }
        public int equipo_a { get; set; }
        public int equipo_b { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime dia_hora { get; set; }
        public int estadio_id { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Equipos Equipos1 { get; set; }
        public virtual Estadio Estadio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gole> Goles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarjeta> Tarjetas { get; set; }
    }
}
