//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial1_PrograIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Percances = new HashSet<Percance>();
        }
    
        public int Id { get; set; }
        public string placa { get; set; }
        public string tipo { get; set; }
        public int marca_id { get; set; }
        public string modelo { get; set; }
        public int anio { get; set; }
        public int motor { get; set; }
        public int gasolina { get; set; }
        public int odometro { get; set; }
        public string color { get; set; }
        public int costo_inicial { get; set; }
        public int costo_variacion { get; set; }
        public string estado { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int llantas { get; set; }
        public int puertas { get; set; }
    
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Percance> Percances { get; set; }
    }
}
